### ISSUE TITLE
v2.x (and possibly 3.x) wrong window size on Windows 8 and high density displays

### ISSUE THREAD

**Issue by djogon** [MSOpenTech/cocos2d-x#137] opened 2015-04-11 16:17 UTC
If a display is not a 96dpi display, but has a greater density like Surface Pro 3 tabled does for example - the core DirectX window is created in DIPs resulting in a window larger by the factor of (device dpi)/96

Seems that Cocos2d-x is calculating and converting DIPs to pixels correctly, but Angle always creates window i DIPs. 

One can temporarily pretend that the device's screen density is always 96dpi and confirm that this is the actual issue. It can also be temporarily fixed like this, but a real fix is needed handling non 96dpi screens better.

**Comment by stammen** [comment] 2015-06-19 15:13
Duplicate of https://github.com/MSOpenTech/cocos2d-x/issues/156

**Closed by stammen** 2015-06-19 15:13 UTC
