### ISSUE TITLE
Wrong Resolution in some wp8 devices

### ISSUE THREAD

**Issue by giuslape** [MSOpenTech/cocos2d-x#58] opened 2014-06-13 16:15 UTC
Developing Lumia 1520 we found that rendered textures are very blurry. Indeed, while that device has a resolution of 1920 x 1080,    
<code>
auto screenSize = glview->getFrameSize();
</code>
give us a down scaled resolution according to:
http://msdn.microsoft.com/en-us/library/windowsphone/develop/jj206974(v=vs.105).aspx

**Comment by stammen** [comment] 2015-06-19 15:11
Duplicate of https://github.com/MSOpenTech/cocos2d-x/issues/156

**Closed by stammen** 2015-06-19 15:11 UTC
Labels: enhancement
