### ISSUE TITLE
Handle Back Key In Universal App cocos2d-x

### ISSUE THREAD

**Issue by alvisstar** [MSOpenTech/cocos2d-x#122] opened 2015-01-22 18:46 UTC
I'm cocos2d-x developer.I have a problem

In wp8 version i can handle back key in by OnBackKeyPressed but in universal app version i can't find way to handle it.App alway go background

**Comment by stammen** [comment] 2015-01-22 18:48
@alvisstar We will work on this as soon as possible and work with you to test the feature in your app. The problem is that the back button event comes in on the wrong thread for cocos2d-x to handle it immediately. The phone, however, needs to know immediately if it can quit the app.

**Comment by alvisstar** [comment] 2015-01-23 04:42
Thanks for support :D

**Comment by zawasp** [comment] 2015-03-23 07:00
Any word on this issue? It's quite critical for any game to handle the back button for in-game navigation. Back button was working on previous cocos2d-x versions.
Thank you.

**Comment by sidshekar** [comment] 2015-03-23 08:33
Ya the back button used to work in 2.x but it would close the App. My app
gets rejected every time due to it. I wish there was a proper
implementation.

**Comment by alvisstar** [comment] 2015-03-24 06:43
i hope you can fix as soon as possible :D.

**Comment by alvisstar** [comment] 2015-03-24 06:57
i hope you can fix as soon as possible :D.

**Comment by stammen** [comment] 2015-04-21 02:00
Fix in pull request

https://github.com/cocos2d/cocos2d-x/pull/11523

**Comment by stammen** [comment] 2015-05-05 04:52
Fix is in cocos2d-x v3.6 release

**Closed by stammen** 2015-05-05 04:52 UTC
Labels: bug, P1, Universal App
